### PR TITLE
Ensure consistent quantities across all study UI. Fixes #58.

### LINKED ISSUE #58: Inconsistent results between awesomebar, dropdown, and new tab
### Steps to reproduce:

1. Run `npm run firefox`.
1. Set `extensions.tracking_protection_messaging_study.variation_override` flag to "fast".
1. Reload temporary extension.
1. Visit https://www.msn.com/en-ca/

### Actual results:

msn_ca

newrtab

Awesome bar says I've saved 7 seconds of my life.
The dropdown menu says 0 trackers blocked and 0 seconds saved.
The new tab page says 0 trackers blocked today and 0.26 minutes saved. (which is roughly 15.6 seconds).

### PR DESCRIPTION
**Pull request by biancadanforth**
I use `Math.ceil` consistently for per-page totals on time saved and total time saved.
I make sure to sum rounded totals for `totalTimeSaved` and `totalBlockedAds` instead of rounding the sum at the end.
@pdehaan Can you try this out and see if this fixes #58?

### CODE REVIEW

File: addon/content/scripts/page-action-panel.js [hunk 1]
```diff
@@ -110,9 +110,9 @@ class PageActionPanel {
         timeUnit += "s";
       }
     } else {
-      timeSaved += `${Math.round(timeSeconds)}`;
+      timeSaved += timeSeconds;
       timeUnit += "second";
-      if (Math.round(timeSeconds) !== 1) {
+      if (timeSaved !== 1) {
```
Comment (pdehaan) [inline addon/content/scripts/page-action-panel.js]: So far everything is looking 💯, but I am seeing a possibly new issue with "1 seconds" being pluralized.

1-seconds-saved

I'm making a wild guess that `timeSaved` is a string (per L102), and then we're concatenating a string on L107. But when we do a plural check on L115, we're checking if the value is `1`. Previously we were using `Math.round()` which was probably auto-casting it to a number, which I don't think is happening any longer.

**Comment by biancadanforth** [comment]
Thanks Peter for catching that! I used the wrong variable there. Should have been `timeSeconds`, not `timeSaved`. It's fixed now.
