### PR TITLE
Remove TODO comments. Fix 'npm run lint'. Fixes #74.

### LINKED ISSUE #74: Clear up all TODO/FIXME comments in code and lint
There are a number of TODOs in the code; before shipping, they should be addressed, the corresponding [eslint rule](https://github.com/biancadanforth/tracking-protection-shield-study/blob/1d7de44f860a5af454f0701e59434bd2654503a9/.eslintrc.js#L44) should be updated and the code should be linted.

### PR DESCRIPTION
**Pull request by biancadanforth**

### CODE REVIEW

File: addon/bootstrap.js [hunk 1]
```diff
@@ -86,7 +86,6 @@ this.Bootstrap = {
     if (!Services.wm.getMostRecentWindow("navigator:browser")) {
       Services.obs.addObserver(this, this.UI_AVAILABLE_NOTIFICATION);
     } else {
-      // TODO bdanforth: check if window is private before adding UI
```
Comment (biancadanforth) [inline addon/bootstrap.js]: Done in #86 .

File: addon/bootstrap.js [hunk 2]
```diff
@@ -112,7 +111,6 @@ this.Bootstrap = {
   initStudyUtils(id, version) {
     // validate study config
     studyUtils.setup({...config, addon: { id, version }});
-    // TODO bdanforth: patch studyUtils to setLoggingLevel as part of setup method
```
Comment (biancadanforth) [inline addon/bootstrap.js]: In the [plans](https://github.com/mozilla/shield-studies-addon-utils/issues/101#issuecomment-367409290) for the next rev of StudyUtils.

File: addon/lib/Config.jsm [hunk 3]
```diff
@@ -15,7 +15,6 @@ XPCOMUtils.defineLazyModuleGetter(this, "Services", "resource://gre/modules/Serv
 
 /* eslint no-unused-vars: ["error", { "varsIgnorePattern": "(config|EXPORTED_SYMBOLS)" }]*/
 const EXPORTED_SYMBOLS = ["config"];
-// TODO change testing survey endings to production survey endings
```
Comment (biancadanforth) [inline addon/lib/Config.jsm]: Done with #23 .

File: addon/lib/Config.jsm [hunk 4]
```diff
@@ -80,7 +79,6 @@ const config = {
     "telemetry": {
       "send": true, // assumed false. Actually send pings?
       "removeTestingFlag": false,  // Marks pings as testing, set true for actual release
-      // TODO "onInvalid": "throw"  // invalid packet for schema?  throw||log
```
Comment (biancadanforth) [inline addon/lib/Config.jsm]: Unclear comment inherited from template. WONTFIX. `Config.jsm` will be getting a facelift when we move to WebExtension Experiments (my next study).

File: addon/lib/Feature.jsm [hunk 5]
```diff
@@ -8,22 +8,37 @@
 /* eslint no-unused-vars: ["error", { "varsIgnorePattern": "(EXPORTED_SYMBOLS|Feature)" }] */
 
 /**
- * What this Feature does: TODO bdanforth: complete
```
Comment (biancadanforth) [inline addon/lib/Feature.jsm]: Completed now!

File: addon/lib/Feature.jsm [hunk 6]
```diff
@@ -584,12 +603,8 @@ class Feature {
   }
 
   /**
-   * Display instrumented 'introductory panel' explaining the feature to the user
-   * Telemetry Probes:
-   *   - {event: introduction-shown}
-   *   - {event: introduction-accept}
-   *   - {event: introduction-leave-study}
-   * Note:  TODO bdanforth: Panel WILL NOT SHOW if the only window open is a private window.
```
Comment (biancadanforth) [inline addon/lib/Feature.jsm]: Done in #86 .

File: addon/lib/Feature.jsm [hunk 7]
```diff
@@ -667,7 +682,6 @@ class Feature {
     } else {
       this.weakPageActionPanel = Cu.getWeakReference(panel);
     }
-    // TODO pass strings and values into this method to show up on the panel
```
Comment (biancadanforth) [inline addon/lib/Feature.jsm]: Done in PR #64 .

File: addon/lib/Feature.jsm [hunk 8]
```diff
@@ -933,15 +947,38 @@ class Feature {
 
   async reimplementTrackingProtection(win) {
     // 1. get blocklist and allowlist
-    // TODO bdanforth: include a doc block with format/content for each
```
Comment (biancadanforth) [inline addon/lib/Feature.jsm]: Completed here.

File: addon/lib/Feature.jsm [hunk 9]
```diff
@@ -1040,10 +1077,9 @@ class Feature {
         const rootDomainHost = this.getRootDomain(host);
         const rootDomainCurrentHost = this.getRootDomain(currentHost);
 
-        // check if host entity is in the entity list;
-        // TODO bdanforth: improve effeciency of this algo
```
Comment (biancadanforth) [inline addon/lib/Feature.jsm]: WONTFIX. No time. Also, perf tests in tree show [no significant, consistent regressions](https://github.com/biancadanforth/tracking-protection-shield-study/issues/26#issuecomment-363272385).

File: package.json [hunk 10]
```diff
@@ -31,6 +31,7 @@
     "eslint-plugin-json": "^1.2.0",
     "eslint-plugin-mozilla": "^0.8.2",
     "eslint-plugin-no-unsanitized": "^3.0.0",
+    "fixpack": "^2.3.1",
```
Comment (biancadanforth) [inline package.json]: Added so `npm run lint` works.
